[2023-06-12 01:40:59,473] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-26T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,517] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-26T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,520] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,528] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-06-12 01:40:59,529] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,570] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): db_connect> on 2023-05-26 00:00:00+00:00
[2023-06-12 01:40:59,603] {standard_task_runner.py:52} INFO - Started process 211 to run task
[2023-06-12 01:40:59,662] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tercera_entrega_ecentoz', 'db_connect', 'scheduled__2023-05-26T00:00:00+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/dag_tercera_entrega.py', '--cfg-path', '/tmp/tmpkkw8eunw', '--error-file', '/tmp/tmp1jfrmce9']
[2023-06-12 01:40:59,691] {standard_task_runner.py:80} INFO - Job 352: Subtask db_connect
[2023-06-12 01:40:59,936] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: FATAL:  the database system is shutting down

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-12 01:40:59,995] {standard_task_runner.py:97} ERROR - Failed to execute job 352 for task db_connect ((psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8); 211)
[2023-06-12 01:41:00,052] {local_task_job.py:156} INFO - Task exited with return code 1
