[2023-06-12 01:40:59,481] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-31T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,556] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-31T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,562] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,563] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-06-12 01:40:59,564] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,626] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): db_connect> on 2023-05-31 00:00:00+00:00
[2023-06-12 01:40:59,675] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tercera_entrega_ecentoz', 'db_connect', 'scheduled__2023-05-31T00:00:00+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/dag_tercera_entrega.py', '--cfg-path', '/tmp/tmp9qfcv344', '--error-file', '/tmp/tmphszhcih0']
[2023-06-12 01:40:59,687] {standard_task_runner.py:52} INFO - Started process 215 to run task
[2023-06-12 01:40:59,696] {standard_task_runner.py:80} INFO - Job 346: Subtask db_connect
[2023-06-12 01:40:59,940] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: FATAL:  the database system is shutting down

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-12 01:41:00,059] {standard_task_runner.py:97} ERROR - Failed to execute job 346 for task db_connect ((psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8); 215)
[2023-06-12 01:41:00,142] {local_task_job.py:156} INFO - Task exited with return code 1
