[2023-06-12 01:40:59,488] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-27T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,582] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tercera_entrega_ecentoz.db_connect scheduled__2023-05-27T00:00:00+00:00 [queued]>
[2023-06-12 01:40:59,585] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,587] {taskinstance.py:1377} INFO - Starting attempt 5 of 6
[2023-06-12 01:40:59,593] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-12 01:40:59,659] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): db_connect> on 2023-05-27 00:00:00+00:00
[2023-06-12 01:40:59,712] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2023-06-12 01:40:59,747] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tercera_entrega_ecentoz', 'db_connect', 'scheduled__2023-05-27T00:00:00+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/dag_tercera_entrega.py', '--cfg-path', '/tmp/tmpdue4ojvb', '--error-file', '/tmp/tmp1hmie4lb']
[2023-06-12 01:40:59,765] {standard_task_runner.py:80} INFO - Job 348: Subtask db_connect
[2023-06-12 01:40:59,900] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: FATAL:  the database system is shutting down

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-12 01:40:59,977] {standard_task_runner.py:97} ERROR - Failed to execute job 348 for task db_connect ((psycopg2.OperationalError) connection to server at "postgres" (172.19.0.2), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8); 218)
[2023-06-12 01:41:00,022] {local_task_job.py:156} INFO - Task exited with return code 1
